### ISSUE TITLE
Blog Shapiro Wilk Test und Gerundete Daten

### ISSUE THREAD

**Issue by phish108** [dxiai/dxiai.github.io#17]
Der Shapiro Wilk Test für Normalität funktioniert bei gerundeten Daten in homogenen Stichproben unzuverlässig. 

- [x] Problembeschreibung
- [x] Erwartetes Verhalten
- [x] Verhalten mit gerundeten Werten
- [x] qq-plots für gerundete Werte
- [x] sd-Grenze ab der SWT nicht mehr geht. 
- [x] Wie löst man das Problem?

**Comment by bajkad** [comment]
Das Beispiel spricht von Alter und einer Abrundung auf den ganzzahligen Wert. Dem würde floor() besser entsprechen als round(). Beim Durchspielen des Shapiro-Tests ergeben sich beim Vergleich von round() und floor() auf die Nullhypothese bezogen relevante Unterschiede im Resultat (Zeilen 105-109).

**Comment by phish108** [comment]
Guter Punkt, @bajkad. 

Die Unterschiede waren bei mir zwar nicht so gewaltig. Aber mit `floor()` ist die Argumentation definitiv konsistenter. Ich habe alle `round ` durch `floor` ersetzt und neu berechnet.
