### ISSUE TITLE
Kann Kernteam Member nicht zu einem Issue assignen

### ISSUE THREAD

**Issue by bajkad** [dxiai/dxiai.github.io#31]
fixes #31

**Comment by bajkad** [comment]
Kann Nuri nicht zu dxiai/zhaw-actup assignen

**Comment by phish108** [comment]
Man kann erst ein Issue einer Person oder einem Team zuweisen, wenn diese einem Repository zugewiesen wurde. Das konfiguriert man unter Einstellungen/Settings und dann unter Members. Für unsere Repos weisen wir normal das `dxiai/core` Tean zu. 

Standardmässig dürfen sonst nur Org-Adnins in den Repos arbeiten. Ich habe noch keinen Weg gefunden, um das pauschal einzustellen für die gesamte Orga einzustellen.

**Comment by phish108** [comment]
Ich habe die Zuweisung gemacht.
